package Utility;

public class Payload {
	
	public static String Payloadtest() {
		return "{\n"
				+ "    \"GroupProperty\": false,\n"
				+ "    \"GroupName\": \"\",\n"
				+ "    \"PropertyList\": {\n"
				+ "        \"514299\": {\n"
				+ "            \"PropertyData\": {\n"
				+ "                \"PropertyId\": \"514299\",\n"
				+ "                \"PropertyName\": \"OctaTest\",\n"
				+ "                \"CSBEStatus\": \"S\",\n"
				+ "                \"PropertyDescription\": \"Graceful Apartment in London in London features accommodation with free WiFi, 600 m from Piccadilly Theatre, 800 m from Prince of Wales Theatre and less than 1 km from Piccadilly Circus. This apartment is 1.4 km from St James Park and 1.4 km from Prince Edward Theatre.This apartment comes with a seating area, a kitchen with a dishwasher, and a TV.Popular points of interest near the apartment include Queen Theatre, Oxford Street and Carnaby Street. The nearest airport is London City Airport, 16 km from Graceful Apartment in London..\",\n"
				+ "                \"Banner\": \"\",\n"
				+ "                \"Logo\": \"\",\n"
				+ "                \"Currency\": \"GBP\",\n"
				+ "                \"Address\": {\n"
				+ "                    \"Location\": \"\",\n"
				+ "                    \"AddressLine\": \"36 Northwild Street\",\n"
				+ "                    \"City\": \"London\",\n"
				+ "                    \"State\": \"Ontario (Canada)\",\n"
				+ "                    \"Country\": \"United Kingdom of Great Britain and Northern Ireland\",\n"
				+ "                    \"CountryCode\": \"GB\",\n"
				+ "                    \"Email\": \"onkar@staah.com\",\n"
				+ "                    \"Phone\": \"+3362211110\",\n"
				+ "                    \"PostalCode\": \"M16JD\"\n"
				+ "                },\n"
				+ "                \"Website\": \"https://www.google.\",\n"
				+ "                \"Timezone\": \"1.00\",\n"
				+ "                \"PropertyDate\": \"2023-04-06\",\n"
				+ "                \"BePermisison\": {\n"
				+ "                    \"BillingAddressRequire\": false,\n"
				+ "                    \"DisableLastUnitPrompt\": false\n"
				+ "                },\n"
				+ "                \"CheckInTime\": \"12:00 am\",\n"
				+ "                \"CheckOutTime\": \"12:00 am\",\n"
				+ "                \"DayuseCheckIn\": \"00:00 am\",\n"
				+ "                \"DayUseCheckOut\": \"00:00 am\",\n"
				+ "                \"CalendarDefLOS\": 1,\n"
				+ "                \"CalendarDefLosFix\": false,\n"
				+ "                \"CollectAllGuestName\": false,\n"
				+ "                \"BillingAddressRequire\": false,\n"
				+ "                \"DisableCheckInTime\": false,\n"
				+ "                \"DisableGuestBookingNotification\": false,\n"
				+ "                \"DisableSubscribeNewsLetter\": false,\n"
				+ "                \"PaymentRequired\": false,\n"
				+ "                \"MultiCurrency\": false,\n"
				+ "                \"CurrencyList\": [\n"
				+ "                    \n"
				+ "                ],\n"
				+ "                \"TaxTitle\": \"Tax Exclusive\",\n"
				+ "                \"MBRCode\": \"MBR\",\n"
				+ "                \"InfantAge\": 0,\n"
				+ "                \"ChildAge\": 16,\n"
				+ "                \"Rating\": \"5\",\n"
				+ "                \"Amenities\": {\n"
				+ "                    \"Facilities\": [\n"
				+ "                        \"24 hours Frontdesk\",\n"
				+ "                        \"CCTV Camera\",\n"
				+ "                        \"Convention Center\",\n"
				+ "                        \"Gym\"\n"
				+ "                    ],\n"
				+ "                    \"Parking\": [\n"
				+ "                        \"Free Parking\"\n"
				+ "                    ]\n"
				+ "                },\n"
				+ "                \"GeoLocation\": {\n"
				+ "                    \"Latitude\": 49.4092,\n"
				+ "                    \"Longitude\": 1.09\n"
				+ "                },\n"
				+ "                \"Images\": [\n"
				+ "                    \"https://suissu.s3.amazonaws.com/images/69c6da2528b429dd7ee0e238df9f504b.jpeg\",\n"
				+ "                    \"https://suissu.s3.amazonaws.com/images/6064ec23762e85936dd0acafa6f535b9.jpeg\",\n"
				+ "                    \"https://suissu.s3.amazonaws.com/images/50b5d9380907b939545c180de34eab72.jpeg\",\n"
				+ "                    \"https://suissu.s3.amazonaws.com/images/5190136c6594eb1e22bc8e37770469ef.jpeg\",\n"
				+ "                    \"https://suissu.s3.amazonaws.com/images/b35aa920c4f6d30727ba1c0a9f420230.jpeg\"\n"
				+ "                ],\n"
				+ "                \"AdditionalFields\": [\n"
				+ "                    \n"
				+ "                ],\n"
				+ "                \"Scripts\": [\n"
				+ "                    \n"
				+ "                ],\n"
				+ "                \"TrafficScript\": {\n"
				+ "                    \"GoogleAnalyticsId\": \"\",\n"
				+ "                    \"GoogleEcomDomainName\": \"\",\n"
				+ "                    \"GoogleAdvConvId\": \"\",\n"
				+ "                    \"GoogleAdvConvLabel\": \"\",\n"
				+ "                    \"GoogleTagMgrId\": \"\",\n"
				+ "                    \"GoogleTagMgrMeta\": \"\"\n"
				+ "                },\n"
				+ "                \"SocialMediaLinks\": {\n"
				+ "                    \"Facebook\": \"\",\n"
				+ "                    \"Instagram\": \"\",\n"
				+ "                    \"Twitter\": \"\",\n"
				+ "                    \"LinkedIn\": \"\",\n"
				+ "                    \"GooglePlus\": \"\",\n"
				+ "                    \"TripAdvisor\": \"\"\n"
				+ "                },\n"
				+ "                \"ChildrenPolicy\": \"\",\n"
				+ "                \"ExtraBedPolicy\": \"\",\n"
				+ "                \"CheckInOutPolicy\": \"\",\n"
				+ "                \"DayuseCheckInPolicy\": \"\",\n"
				+ "                \"EarlyCheckInNotes\": \"\",\n"
				+ "                \"SmokingPolicy\": \"\",\n"
				+ "                \"OtherPolicy\": \"\",\n"
				+ "                \"CreditCardTerms\": null,\n"
				+ "                \"CustomerSupport\": \"\",\n"
				+ "                \"PaymentTerms\": {\n"
				+ "                    \"Header\": \"\",\n"
				+ "                    \"Description\": \"<h1 style=\\\"text-align: justify;\\\"><b>100% Advance</b></h1>\"\n"
				+ "                },\n"
				+ "                \"PaymentHeader\": {\n"
				+ "                    \"Hide\": true,\n"
				+ "                    \"Description\": \"\"\n"
				+ "                },\n"
				+ "                \"TermsAndConditions\": {\n"
				+ "                    \"Header\": \"\",\n"
				+ "                    \"Description\": \"<p>1)Booking is not Refundable</p>\",\n"
				+ "                    \"URL\": \"\"\n"
				+ "                },\n"
				+ "                \"PrivacyStatement\": {\n"
				+ "                    \"Hide\": true,\n"
				+ "                    \"Description\": \"OctaTest is committed to privacy for everyone who accesses our website. This site, OctaTest, only collects personal data about you as needed to provide you with outstanding service, and to help process your request or provide you with information.\"\n"
				+ "                },\n"
				+ "                \"SoldoutPrompt\": {\n"
				+ "                    \"Hide\": false,\n"
				+ "                    \"Description\": \"Property is not bookable during these dates, please try different dates or alternatively contact us on onkar@staah.com\"\n"
				+ "                },\n"
				+ "                \"PrivacyPolicy\": {\n"
				+ "                    \"Type\": \"link\",\n"
				+ "                    \"Description\": \"<p style='padding:10px 0;letter-spacing:0;line-height:normal'>This privacy policy sets out how we use and protects any information that you give us when you use this website. We are committed to ensuring that your privacy is protected. Should we ask you to provide certain information by which you can be identified when using this website, then you can be assured that it will only be used in accordance with this privacy statement. We may change this policy from time to time by updating this page. You should check this page from time to time to ensure that you are happy with any changes.</p><h3 style='padding:10px 0'>WHAT WE COLLECT</h3><p style='padding:10px 0;letter-spacing:0;line-height:normal'>We may collect the following information:</p><ul style='padding:10px 0;list-style:disc;margin:0 15px;font-size:14px;font-weight:400;color:#424040'><li>Name and job title</li><li>Contact information including email address</li><li>Demographic information such as postcode, preferences and interests</li></ul><h3 style='padding:10px 0'>WHAT WE DO WITH THE INFORMATION WE GATHER</h3><p style='padding:10px 0;letter-spacing:0;line-height:normal'>We require this information to understand your needs and provide you with a better service and for the following reasons:</p><ul style='padding:10px 0;list-style:disc;margin:0 15px;font-size:14px;font-weight:400;color:#424040'><li>Internal record keeping</li><li>We may use the information to improve our products and services</li><li>We may periodically send promotional email about new products, special offers or other information which we think you may find interesting using the email address which you have provided. To do this you need to opt in for this serice</li><li>We may contact you by email, phone or mail</li><li>We may use the information to customise the website according to your interests</li></ul><h3 style='padding:10px 0'>SECURITY</h3><p style='padding:10px 0;letter-spacing:0;line-height:normal'>We are committed to ensuring that your information is secure. To prevent unauthorised access or disclosure we have put in place suitable physical, electronic and managerial procedures to safeguard and secure the information we collect online.</p><h3 style='padding:10px 0'>HOW WE USE COOKIES</h3><p style='padding:10px 0;letter-spacing:0;line-height:normal'>A cookie is an element of data that a website can send to your browser, which may then store it on your system. We use cookies in some of our pages to store your preferences and record session information. The information that we collect is then used to ensure a more personalized service level for our users. Please be assured though that your credit card number will not be saved for security reasons. You must type the credit card number each time you make a purchase. You can adjust settings on your browser so that you will be notified when you receive a cookie. Please refer to your browser documentation to check if cookies have been enabled on your computer or to request not to receive cookies. As cookies allow you to take advantage of some of the Website’s essential features, we recommend that you accept cookies. This information is treated confidentially and will not be shared with anyone outside of the Company unless otherwise stated in the Privacy Policy. We will only use this information to make informed decisions regarding the purchase of online advertising.</p><h3 style='padding:10px 0'>LINKS TO OTHER WEBSITES</h3><p style='padding:10px 0;letter-spacing:0;line-height:normal'>Our website may contain links to enable you to visit other websites of interest easily. However, once you have used these links to leave our site, you should note that we do not have any control over that other website. Therefore, we cannot be responsible for the protection and privacy of any information which you provide whilst visiting such sites and such sites are not governed by this privacy statement. You should exercise caution and look at the privacy statement applicable to the website in question.</p><h3 style='padding:10px 0'>CONTROLLING YOUR PERSONAL INFORMATION</h3><p style='padding:10px 0;letter-spacing:0;line-height:normal'>You may choose to restrict the collection or use of your personal information in the following ways:</p><ul style='padding:10px 0;list-style:disc;margin:0 15px;font-size:14px;font-weight:400;color:#424040'><li>We will not sell, distribute of lease your personal information to third parties unless we have your permission or are required by law to do so</li><li>You may request details of personal information which we hold about you under the Data Protection Act 1998</li><li>If you believe that any information which we are holding on you is incorrect or incomplete, please wrote to or email us as soon as possible. We will promptly correct any information found to be incorrect</li></ul>\"\n"
				+ "                },\n"
				+ "                \"BeOtherText\": {\n"
				+ "                    \"Hide\": true,\n"
				+ "                    \"Description\": \"\"\n"
				+ "                },\n"
				+ "                \"BookingConfirmation\": {\n"
				+ "                    \"Hide\": true,\n"
				+ "                    \"Description\": \"\"\n"
				+ "                },\n"
				+ "                \"CovidPolicy\": {\n"
				+ "                    \"Hide\": true,\n"
				+ "                    \"DisplayLabel\": \"\",\n"
				+ "                    \"MessageforVaccinatedGuest\": \"\",\n"
				+ "                    \"MessageforNonVaccinatedGuest\": \"\"\n"
				+ "                },\n"
				+ "                \"Meta\": {\n"
				+ "                    \"KeyWord\": \"\",\n"
				+ "                    \"Description\": \"\",\n"
				+ "                    \"Favicon\": \"\"\n"
				+ "                },\n"
				+ "                \"EarlyCheckInPolicy\": \"\",\n"
				+ "                \"ReviewMinderEnable\": false,\n"
				+ "                \"BeAlert\": [\n"
				+ "                    \n"
				+ "                ],\n"
				+ "                \"DecimalRateManual\": true,\n"
				+ "                \"DecimalRate\": true,\n"
				+ "                \"CustomScript\": \"\",\n"
				+ "                \"PosUrl\": \"https://pos.staah.net/?propertyId=param-property-id&checkIn=yyyy-mm-dd&checkOut=yyyy-mm-dd&noOfAdult=NoAdult&noOfChild=NoChild&currency=User-Currency&source=SourceName\",\n"
				+ "                \"TrackerId\": \"514299\"\n"
				+ "            },\n"
				+ "            \"RoomData\": {\n"
				+ "                \"1144\": {\n"
				+ "                    \"RoomId\": \"1144\",\n"
				+ "                    \"RoomName\": \"Deluxe Double Room with Sea  View\",\n"
				+ "                    \"RoomDisplayName\": \"Deluxe Double Room with Sea  View\",\n"
				+ "                    \"LastUnitPrompt\": \"Room\",\n"
				+ "                    \"RoomDescription\": \"TxtTest\",\n"
				+ "                    \"MaxGuest\": 2,\n"
				+ "                    \"MaxAdult\": 2,\n"
				+ "                    \"MaxChildren\": 1,\n"
				+ "                    \"Fees\": [\n"
				+ "                        \n"
				+ "                    ],\n"
				+ "                    \"ExtraAdultRate\": 0,\n"
				+ "                    \"ExtraChildRate\": 0,\n"
				+ "                    \"RoomView\": \"\",\n"
				+ "                    \"RackRate\": \"50\",\n"
				+ "                    \"Bedding\": [\n"
				+ "                        {\n"
				+ "                            \"Beds\": 1,\n"
				+ "                            \"BedType\": \"King\",\n"
				+ "                            \"Id\": 2,\n"
				+ "                            \"Active\": true,\n"
				+ "                            \"Icon\": \"\"\n"
				+ "                        }\n"
				+ "                    ],\n"
				+ "                    \"ShowBeddingConf\": \"Y\",\n"
				+ "                    \"BeddingOptional\": true,\n"
				+ "                    \"RoomSize\": \"16:sqm\",\n"
				+ "                    \"DisableChildren\": false,\n"
				+ "                    \"Address\": {\n"
				+ "                        \n"
				+ "                    },\n"
				+ "                    \"GeoLocation\": {\n"
				+ "                        \"Latitude\": \"\",\n"
				+ "                        \"Longitude\": \"\"\n"
				+ "                    },\n"
				+ "                    \"Images\": [\n"
				+ "                        \"https://suissu.s3.amazonaws.com/images/9edf74f43d393745c71f200648c3d04d.jpeg\",\n"
				+ "                        \"https://suissu.s3.amazonaws.com/images/5407d2be29015276abb845b92f43c443.jpeg\",\n"
				+ "                        \"https://suissu.s3.amazonaws.com/images/93987db07ec820746f4251071f5b6d19.jpeg\",\n"
				+ "                        \"https://suissu.s3.amazonaws.com/images/97e412be2264ccd5a08bf43c59df038d.jpeg\"\n"
				+ "                    ],\n"
				+ "                    \"RoomAmenities\": {\n"
				+ "                        \"Amenities\": [\n"
				+ "                            \"Free Wifi\",\n"
				+ "                            \"Hairdyer\",\n"
				+ "                            \"Iron Facilities\"\n"
				+ "                        ],\n"
				+ "                        \"Facilities\": [\n"
				+ "                            \"24 hours Frontdesk\",\n"
				+ "                            \"CCTV Camera\",\n"
				+ "                            \"Convention Center\",\n"
				+ "                            \"Gym\"\n"
				+ "                        ],\n"
				+ "                        \"Kitchen\": [\n"
				+ "                            \"Coffee Maker\",\n"
				+ "                            \"Microwave\"\n"
				+ "                        ],\n"
				+ "                        \"Parking\": [\n"
				+ "                            \"Free Parking\"\n"
				+ "                        ]\n"
				+ "                    },\n"
				+ "                    \"ParentRoomId\": \"0\",\n"
				+ "                    \"IsMaster\": true,\n"
				+ "                    \"Priority\": 0,\n"
				+ "                    \"CurrId\": \"0\",\n"
				+ "                    \"CurrName\": \"GBP\"\n"
				+ "                },\n"
				+ "                \"STD\": {\n"
				+ "                    \"RoomId\": \"STD\",\n"
				+ "                    \"RoomName\": \"BAT\",\n"
				+ "                    \"RoomDisplayName\": \"BAT\",\n"
				+ "                    \"LastUnitPrompt\": \"Room\",\n"
				+ "                    \"RoomDescription\": \"TESTA1221\",\n"
				+ "                    \"MaxGuest\": 2,\n"
				+ "                    \"MaxAdult\": 2,\n"
				+ "                    \"MaxChildren\": 1,\n"
				+ "                    \"Fees\": [\n"
				+ "                        \n"
				+ "                    ],\n"
				+ "                    \"ExtraAdultRate\": 0,\n"
				+ "                    \"ExtraChildRate\": 0,\n"
				+ "                    \"RoomView\": \"\",\n"
				+ "                    \"RackRate\": \"50\",\n"
				+ "                    \"Bedding\": [\n"
				+ "                        {\n"
				+ "                            \"Beds\": 1,\n"
				+ "                            \"BedType\": \"Double\",\n"
				+ "                            \"Id\": 1,\n"
				+ "                            \"Active\": true,\n"
				+ "                            \"Icon\": \"\"\n"
				+ "                        }\n"
				+ "                    ],\n"
				+ "                    \"ShowBeddingConf\": \"Y\",\n"
				+ "                    \"BeddingOptional\": true,\n"
				+ "                    \"RoomSize\": \"16:sqm\",\n"
				+ "                    \"DisableChildren\": false,\n"
				+ "                    \"Address\": {\n"
				+ "                        \n"
				+ "                    },\n"
				+ "                    \"GeoLocation\": {\n"
				+ "                        \"Latitude\": \"\",\n"
				+ "                        \"Longitude\": \"\"\n"
				+ "                    },\n"
				+ "                    \"Images\": [\n"
				+ "                        \"https://suissu.s3.amazonaws.com/images/93987db07ec820746f4251071f5b6d19.jpeg\"\n"
				+ "                    ],\n"
				+ "                    \"RoomAmenities\": {\n"
				+ "                        \"Amenities\": [\n"
				+ "                            \"Free Wifi\",\n"
				+ "                            \"Hairdyer\",\n"
				+ "                            \"Iron Facilities\"\n"
				+ "                        ],\n"
				+ "                        \"Facilities\": [\n"
				+ "                            \"24 hours Frontdesk\",\n"
				+ "                            \"CCTV Camera\",\n"
				+ "                            \"Convention Center\",\n"
				+ "                            \"Gym\"\n"
				+ "                        ],\n"
				+ "                        \"Kitchen\": [\n"
				+ "                            \"Coffee Maker\",\n"
				+ "                            \"Microwave\"\n"
				+ "                        ],\n"
				+ "                        \"Parking\": [\n"
				+ "                            \"Free Parking\"\n"
				+ "                        ]\n"
				+ "                    },\n"
				+ "                    \"ParentRoomId\": \"0\",\n"
				+ "                    \"IsMaster\": true,\n"
				+ "                    \"Priority\": 0,\n"
				+ "                    \"CurrId\": \"0\",\n"
				+ "                    \"CurrName\": \"GBP\"\n"
				+ "                },\n"
				+ "                \"TAR\": {\n"
				+ "                    \"RoomId\": \"TAR\",\n"
				+ "                    \"RoomName\": \"TAR\",\n"
				+ "                    \"RoomDisplayName\": \"TAR\",\n"
				+ "                    \"LastUnitPrompt\": \"4\",\n"
				+ "                    \"RoomDescription\": \"TARDESCRIPTION\",\n"
				+ "                    \"MaxGuest\": 2,\n"
				+ "                    \"MaxAdult\": 2,\n"
				+ "                    \"MaxChildren\": 1,\n"
				+ "                    \"Fees\": [\n"
				+ "                        \n"
				+ "                    ],\n"
				+ "                    \"ExtraAdultRate\": 0,\n"
				+ "                    \"ExtraChildRate\": 0,\n"
				+ "                    \"RoomView\": \"\",\n"
				+ "                    \"RackRate\": \"50\",\n"
				+ "                    \"Bedding\": [\n"
				+ "                        {\n"
				+ "                            \"Beds\": 1,\n"
				+ "                            \"BedType\": \"Split King\",\n"
				+ "                            \"Id\": 1,\n"
				+ "                            \"Active\": true,\n"
				+ "                            \"Icon\": \"\"\n"
				+ "                        }\n"
				+ "                    ],\n"
				+ "                    \"ShowBeddingConf\": \"Y\",\n"
				+ "                    \"BeddingOptional\": true,\n"
				+ "                    \"RoomSize\": \"16:sqm\",\n"
				+ "                    \"DisableChildren\": false,\n"
				+ "                    \"Address\": {\n"
				+ "                        \n"
				+ "                    },\n"
				+ "                    \"GeoLocation\": {\n"
				+ "                        \"Latitude\": \"\",\n"
				+ "                        \"Longitude\": \"\"\n"
				+ "                    },\n"
				+ "                    \"Images\": [\n"
				+ "                        \"https://suissu.s3.amazonaws.com/images/97e412be2264ccd5a08bf43c59df038d.jpeg\"\n"
				+ "                    ],\n"
				+ "                    \"RoomAmenities\": {\n"
				+ "                        \"Amenities\": [\n"
				+ "                            \"Free Wifi\",\n"
				+ "                            \"Hairdyer\",\n"
				+ "                            \"Iron Facilities\"\n"
				+ "                        ],\n"
				+ "                        \"Facilities\": [\n"
				+ "                            \"24 hours Frontdesk\",\n"
				+ "                            \"CCTV Camera\",\n"
				+ "                            \"Convention Center\",\n"
				+ "                            \"Gym\"\n"
				+ "                        ],\n"
				+ "                        \"Kitchen\": [\n"
				+ "                            \"Coffee Maker\",\n"
				+ "                            \"Microwave\"\n"
				+ "                        ],\n"
				+ "                        \"Parking\": [\n"
				+ "                            \"Free Parking\"\n"
				+ "                        ]\n"
				+ "                    },\n"
				+ "                    \"ParentRoomId\": \"0\",\n"
				+ "                    \"IsMaster\": true,\n"
				+ "                    \"Priority\": 0,\n"
				+ "                    \"CurrId\": \"0\",\n"
				+ "                    \"CurrName\": \"GBP\"\n"
				+ "                }\n"
				+ "            },\n"
				+ "            \"RateData\": {\n"
				+ "                \"STAR\": {\n"
				+ "                    \"RateId\": \"STAR\",\n"
				+ "                    \"RateName\": \"BAR\",\n"
				+ "                    \"RateDescription\": \"max Daily Rate of the Rate Plan1\",\n"
				+ "                    \"IgnoreTaxes\": \"\",\n"
				+ "                    \"AppliedSmartPrice\": \"5001,5004,5003,5005\"\n"
				+ "                },\n"
				+ "                \"BAT\": {\n"
				+ "                    \"RateId\": \"BAT\",\n"
				+ "                    \"RateName\": \"BAT\",\n"
				+ "                    \"RateDescription\": \"Best Rate Available Rate Plan\",\n"
				+ "                    \"IgnoreTaxes\": \"\",\n"
				+ "                    \"AppliedSmartPrice\": \"5001\"\n"
				+ "                },\n"
				+ "                \"TAR\": {\n"
				+ "                    \"RateId\": \"TAR\",\n"
				+ "                    \"RateName\": \"TAR\",\n"
				+ "                    \"RateDescription\": \"Best Rate Available Rate Plan\",\n"
				+ "                    \"IgnoreTaxes\": \"\",\n"
				+ "                    \"AppliedSmartPrice\": \"5001\"\n"
				+ "                }\n"
				+ "            },\n"
				+ "            \"Mapping\": {\n"
				+ "                \"1144\": {\n"
				+ "                    \"STAR\": {\n"
				+ "                        \"MappingId\": \"1144_STAR\",\n"
				+ "                        \"MappingName\": \"BAR\",\n"
				+ "                        \"RoomId\": \"1144\",\n"
				+ "                        \"RateId\": \"STAR\",\n"
				+ "                        \"Meal\": \"Dinner bed and breakfast plan\",\n"
				+ "                        \"NightType\": \"R\",\n"
				+ "                        \"Private\": false,\n"
				+ "                        \"IncludedExtras\": [\n"
				+ "                            \n"
				+ "                        ],\n"
				+ "                        \"MandatoryExtras\": [\n"
				+ "                            \n"
				+ "                        ],\n"
				+ "                        \"DisableExtras\": \"\",\n"
				+ "                        \"CancellationPolicyID\": 126,\n"
				+ "                        \"CancellationPolicyType\": \"NR\",\n"
				+ "                        \"CancellationPolicy\": \"The guest shall be charged the total price if cancelled.\",\n"
				+ "                        \"PackageRate\": 50.0,\n"
				+ "                        \"MinPackageRate\": 50.0,\n"
				+ "                        \"ExAdRate\": \"0\",\n"
				+ "                        \"ExChildRate\": \"0\",\n"
				+ "                        \"ApplicableGuest\": 0,\n"
				+ "                        \"DefaultMinimumStay\": 1,\n"
				+ "                        \"Image\": \"\",\n"
				+ "                        \"AdvancePurchase\": 0,\n"
				+ "                        \"AppliedPromoCode\": \"5077,5072,5071,\",\n"
				+ "                        \"Validity\": [\n"
				+ "                            \n"
				+ "                        ],\n"
				+ "                        \"ExpireCanPolicy\": \"THIS IS Expired.\"\n"
				+ "                    }\n"
				+ "                },\n"
				+ "                \"STD\": {\n"
				+ "                    \"BAT\": {\n"
				+ "                        \"MappingId\": \"STD_BAT\",\n"
				+ "                        \"MappingName\": \"BAT\",\n"
				+ "                        \"RoomId\": \"STD\",\n"
				+ "                        \"RateId\": \"BAT\",\n"
				+ "                        \"Meal\": \"Bed & breakfast\",\n"
				+ "                        \"NightType\": \"R\",\n"
				+ "                        \"Private\": false,\n"
				+ "                        \"IncludedExtras\": [\n"
				+ "                            \n"
				+ "                        ],\n"
				+ "                        \"MandatoryExtras\": [\n"
				+ "                            \n"
				+ "                        ],\n"
				+ "                        \"DisableExtras\": \"\",\n"
				+ "                        \"CancellationPolicyID\": 0,\n"
				+ "                        \"CancellationPolicyType\": \"\",\n"
				+ "                        \"CancellationPolicy\": \"\",\n"
				+ "                        \"PackageRate\": 50.0,\n"
				+ "                        \"MinPackageRate\": 50.0,\n"
				+ "                        \"ExAdRate\": \"0\",\n"
				+ "                        \"ExChildRate\": \"0\",\n"
				+ "                        \"ApplicableGuest\": 0,\n"
				+ "                        \"DefaultMinimumStay\": 1,\n"
				+ "                        \"Image\": \"\",\n"
				+ "                        \"AdvancePurchase\": 0,\n"
				+ "                        \"AppliedPromoCode\": \"5072,5071,5077,\",\n"
				+ "                        \"Validity\": [\n"
				+ "                            \n"
				+ "                        ],\n"
				+ "                        \"ExpireCanPolicy\": \"THIS IS Expired.\"\n"
				+ "                    }\n"
				+ "                },\n"
				+ "                \"TAR\": {\n"
				+ "                    \"TAR\": {\n"
				+ "                        \"MappingId\": \"TAR_TAR\",\n"
				+ "                        \"MappingName\": \"TAR\",\n"
				+ "                        \"RoomId\": \"TAR\",\n"
				+ "                        \"RateId\": \"TAR\",\n"
				+ "                        \"Meal\": \"Continental breakfast\",\n"
				+ "                        \"NightType\": \"R\",\n"
				+ "                        \"Private\": false,\n"
				+ "                        \"IncludedExtras\": [\n"
				+ "                            \n"
				+ "                        ],\n"
				+ "                        \"MandatoryExtras\": [\n"
				+ "                            \n"
				+ "                        ],\n"
				+ "                        \"DisableExtras\": \"\",\n"
				+ "                        \"CancellationPolicyID\": 125,\n"
				+ "                        \"CancellationPolicyType\": \"NR\",\n"
				+ "                        \"CancellationPolicy\": \"The guest shall be charged the total price if cancelled.\",\n"
				+ "                        \"PackageRate\": 50.0,\n"
				+ "                        \"MinPackageRate\": 50.0,\n"
				+ "                        \"ExAdRate\": \"0\",\n"
				+ "                        \"ExChildRate\": \"0\",\n"
				+ "                        \"ApplicableGuest\": 0,\n"
				+ "                        \"DefaultMinimumStay\": 1,\n"
				+ "                        \"Image\": \"\",\n"
				+ "                        \"AdvancePurchase\": 0,\n"
				+ "                        \"AppliedPromoCode\": \"5072,5071,5077,\",\n"
				+ "                        \"Validity\": [\n"
				+ "                            \n"
				+ "                        ],\n"
				+ "                        \"ExpireCanPolicy\": \"THIS IS Expired.\"\n"
				+ "                    }\n"
				+ "                }\n"
				+ "            },\n"
				+ "            \"ExtrasData\": {\n"
				+ "                \"5077\": {\n"
				+ "                    \"AddonId\": \"5077\",\n"
				+ "                    \"AddonName\": \"Swiming Pool\",\n"
				+ "                    \"AddonDescription\": \"SwimingPool\",\n"
				+ "                    \"Priority\": 0,\n"
				+ "                    \"Applicable\": \"G\",\n"
				+ "                    \"Image\": \"\",\n"
				+ "                    \"Type\": \"R\",\n"
				+ "                    \"ValueType\": \"F\",\n"
				+ "                    \"Rate\": [\n"
				+ "                        \n"
				+ "                    ],\n"
				+ "                    \"AdultRate\": [\n"
				+ "                        {\n"
				+ "                            \"GBP\": {\n"
				+ "                                \"amount\": \"100.00\",\n"
				+ "                                \"tax\": 0,\n"
				+ "                                \"taxes\": [\n"
				+ "                                    \n"
				+ "                                ],\n"
				+ "                                \"amountAfterTax\": \"100.00\"\n"
				+ "                            }\n"
				+ "                        }\n"
				+ "                    ],\n"
				+ "                    \"ChildRate\": [\n"
				+ "                        {\n"
				+ "                            \"GBP\": {\n"
				+ "                                \"amount\": \"50.00\",\n"
				+ "                                \"tax\": 0,\n"
				+ "                                \"taxes\": [\n"
				+ "                                    \n"
				+ "                                ],\n"
				+ "                                \"amountAfterTax\": \"50.00\"\n"
				+ "                            }\n"
				+ "                        }\n"
				+ "                    ],\n"
				+ "                    \"MandatoryRoomIds\": \"\",\n"
				+ "                    \"OtherPackages\": {\n"
				+ "                        \n"
				+ "                    },\n"
				+ "                    \"Validity\": [\n"
				+ "                        \n"
				+ "                    ],\n"
				+ "                    \"WeekDaywiseRateType\": \"\",\n"
				+ "                    \"WeekDaywiseRate\": [\n"
				+ "                        \n"
				+ "                    ]\n"
				+ "                },\n"
				+ "                \"5078\": {\n"
				+ "                    \"AddonId\": \"5078\",\n"
				+ "                    \"AddonName\": \"ClubHouse\",\n"
				+ "                    \"AddonDescription\": \"ClubHouse\",\n"
				+ "                    \"Priority\": 0,\n"
				+ "                    \"Applicable\": \"D\",\n"
				+ "                    \"Image\": \"https://suissu.s3.amazonaws.com/images/cbde72b9b867baa289c19ba294d39c2c.jpg\",\n"
				+ "                    \"Type\": \"R\",\n"
				+ "                    \"ValueType\": \"F\",\n"
				+ "                    \"Rate\": [\n"
				+ "                        {\n"
				+ "                            \"GBP\": {\n"
				+ "                                \"amount\": \"50.00\",\n"
				+ "                                \"tax\": 0,\n"
				+ "                                \"taxes\": [\n"
				+ "                                    \n"
				+ "                                ],\n"
				+ "                                \"amountAfterTax\": \"50.00\"\n"
				+ "                            }\n"
				+ "                        }\n"
				+ "                    ],\n"
				+ "                    \"AdultRate\": [\n"
				+ "                        \n"
				+ "                    ],\n"
				+ "                    \"ChildRate\": [\n"
				+ "                        \n"
				+ "                    ],\n"
				+ "                    \"MandatoryRoomIds\": \"\",\n"
				+ "                    \"OtherPackages\": {\n"
				+ "                        \n"
				+ "                    },\n"
				+ "                    \"Validity\": [\n"
				+ "                        \n"
				+ "                    ],\n"
				+ "                    \"WeekDaywiseRateType\": \"\",\n"
				+ "                    \"WeekDaywiseRate\": [\n"
				+ "                        \n"
				+ "                    ]\n"
				+ "                },\n"
				+ "                \"5079\": {\n"
				+ "                    \"AddonId\": \"5079\",\n"
				+ "                    \"AddonName\": \"Gamezone\",\n"
				+ "                    \"AddonDescription\": \"Gamezone\",\n"
				+ "                    \"Priority\": 0,\n"
				+ "                    \"Applicable\": \"D\",\n"
				+ "                    \"Image\": \"https://suissu.s3.amazonaws.com/images/505e24130fce7102ebca4c00d267407e.jpg\",\n"
				+ "                    \"Type\": \"R\",\n"
				+ "                    \"ValueType\": \"F\",\n"
				+ "                    \"Rate\": [\n"
				+ "                        {\n"
				+ "                            \"GBP\": {\n"
				+ "                                \"amount\": \"100.00\",\n"
				+ "                                \"tax\": 0,\n"
				+ "                                \"taxes\": [\n"
				+ "                                    \n"
				+ "                                ],\n"
				+ "                                \"amountAfterTax\": \"100.00\"\n"
				+ "                            }\n"
				+ "                        }\n"
				+ "                    ],\n"
				+ "                    \"AdultRate\": [\n"
				+ "                        \n"
				+ "                    ],\n"
				+ "                    \"ChildRate\": [\n"
				+ "                        \n"
				+ "                    ],\n"
				+ "                    \"MandatoryRoomIds\": \"\",\n"
				+ "                    \"OtherPackages\": {\n"
				+ "                        \n"
				+ "                    },\n"
				+ "                    \"Validity\": [\n"
				+ "                        \n"
				+ "                    ],\n"
				+ "                    \"WeekDaywiseRateType\": \"\",\n"
				+ "                    \"WeekDaywiseRate\": [\n"
				+ "                        \n"
				+ "                    ]\n"
				+ "                }\n"
				+ "            },\n"
				+ "            \"TaxData\": {\n"
				+ "                \"1\": {\n"
				+ "                    \"TaxId\": \"1\",\n"
				+ "                    \"TaxName\": \"SGST\",\n"
				+ "                    \"TaxDescription\": \"SGST\",\n"
				+ "                    \"TaxType\": \"Flat\",\n"
				+ "                    \"PeriodFrom\": \"01-1\",\n"
				+ "                    \"PeriodTo\": \"12-31\",\n"
				+ "                    \"ValueType\": \"P\",\n"
				+ "                    \"value\": {\n"
				+ "                        \"GBP\": \"10\"\n"
				+ "                    },\n"
				+ "                    \"ApplytoConvertDirect\": true,\n"
				+ "                    \"TaxRackRate\": false,\n"
				+ "                    \"TaxOnTax\": true,\n"
				+ "                    \"TaxableSurcharge\": false,\n"
				+ "                    \"TaxExtrasOnly\": false\n"
				+ "                },\n"
				+ "                \"2\": {\n"
				+ "                    \"TaxId\": \"2\",\n"
				+ "                    \"TaxName\": \"CGST\",\n"
				+ "                    \"TaxDescription\": \"CGST\",\n"
				+ "                    \"TaxType\": \"Flat\",\n"
				+ "                    \"PeriodFrom\": \"01-1\",\n"
				+ "                    \"PeriodTo\": \"12-31\",\n"
				+ "                    \"ValueType\": \"P\",\n"
				+ "                    \"value\": {\n"
				+ "                        \"GBP\": \"15\"\n"
				+ "                    },\n"
				+ "                    \"ApplytoConvertDirect\": true,\n"
				+ "                    \"TaxRackRate\": false,\n"
				+ "                    \"TaxOnTax\": true,\n"
				+ "                    \"TaxableSurcharge\": false,\n"
				+ "                    \"TaxExtrasOnly\": false\n"
				+ "                }\n"
				+ "            },\n"
				+ "            \"SmartPriceData\": {\n"
				+ "                \"5001\": {\n"
				+ "                    \"name\": \"Advance Purchase\",\n"
				+ "                    \"type\": \"AP\",\n"
				+ "                    \"applyPromoAfterSp\": false,\n"
				+ "                    \"discountID\": \"5001\",\n"
				+ "                    \"extraInfo\": {\n"
				+ "                        \"discounts\": [\n"
				+ "                            {\n"
				+ "                                \"value\": 0.0,\n"
				+ "                                \"multiplier\": 1.0,\n"
				+ "                                \"applicable\": 1,\n"
				+ "                                \"discountID\": \"5001\"\n"
				+ "                            }\n"
				+ "                        ],\n"
				+ "                        \"dates\": [\n"
				+ "                            {\n"
				+ "                                \"bookingFromDate\": \"0000-00-00\",\n"
				+ "                                \"bookingToDate\": \"0000-00-00\",\n"
				+ "                                \"stayFromDate\": \"0000-00-00\",\n"
				+ "                                \"stayToDate\": \"0000-00-00\"\n"
				+ "                            }\n"
				+ "                        ],\n"
				+ "                        \"applyToWeekDays\": \"M,T,W,Th,F,S,Su\",\n"
				+ "                        \"blockoutDates\": {\n"
				+ "                            \"blockOutBooking\": \"2023-03-24,2023-03-25\",\n"
				+ "                            \"blockOutStay\": \"\"\n"
				+ "                        }\n"
				+ "                    }\n"
				+ "                },\n"
				+ "                \"5004\": {\n"
				+ "                    \"name\": \"Geo\",\n"
				+ "                    \"type\": \"R\",\n"
				+ "                    \"applyPromoAfterSp\": false,\n"
				+ "                    \"discountID\": \"5004\",\n"
				+ "                    \"extraInfo\": {\n"
				+ "                        \"discounts\": [\n"
				+ "                            {\n"
				+ "                                \"value\": 50.0,\n"
				+ "                                \"multiplier\": 1.0,\n"
				+ "                                \"applicable\": \"AR\",\n"
				+ "                                \"discountID\": \"5004\"\n"
				+ "                            }\n"
				+ "                        ],\n"
				+ "                        \"dates\": [\n"
				+ "                            {\n"
				+ "                                \"bookingFromDate\": \"0000-00-00\",\n"
				+ "                                \"bookingToDate\": \"0000-00-00\",\n"
				+ "                                \"stayFromDate\": \"0000-00-00\",\n"
				+ "                                \"stayToDate\": \"0000-00-00\"\n"
				+ "                            }\n"
				+ "                        ],\n"
				+ "                        \"applyToWeekDays\": \"M,T,W,Th,F,S,Su\",\n"
				+ "                        \"blockoutDates\": {\n"
				+ "                            \"blockOutBooking\": \"\",\n"
				+ "                            \"blockOutStay\": \"\"\n"
				+ "                        }\n"
				+ "                    }\n"
				+ "                },\n"
				+ "                \"5003\": {\n"
				+ "                    \"name\": \"Mobile\",\n"
				+ "                    \"type\": \"D\",\n"
				+ "                    \"applyPromoAfterSp\": false,\n"
				+ "                    \"discountID\": 5003,\n"
				+ "                    \"extraInfo\": {\n"
				+ "                        \"discounts\": [\n"
				+ "                            {\n"
				+ "                                \"value\": -30.0,\n"
				+ "                                \"multiplier\": 1.0,\n"
				+ "                                \"applicable\": \"Mobile\",\n"
				+ "                                \"discountID\": 5003\n"
				+ "                            }\n"
				+ "                        ],\n"
				+ "                        \"dates\": [\n"
				+ "                            {\n"
				+ "                                \"bookingFromDate\": \"0000-00-00\",\n"
				+ "                                \"bookingToDate\": \"0000-00-00\",\n"
				+ "                                \"stayFromDate\": \"0000-00-00\",\n"
				+ "                                \"stayToDate\": \"0000-00-00\"\n"
				+ "                            }\n"
				+ "                        ],\n"
				+ "                        \"applyToWeekDays\": \"M,T,W,Th,F,S,Su\",\n"
				+ "                        \"blockoutDates\": {\n"
				+ "                            \"blockOutBooking\": \"\",\n"
				+ "                            \"blockOutStay\": \"\"\n"
				+ "                        }\n"
				+ "                    }\n"
				+ "                },\n"
				+ "                \"5005\": {\n"
				+ "                    \"name\": \"Discount Per Stay\",\n"
				+ "                    \"type\": \"F\",\n"
				+ "                    \"applyPromoAfterSp\": false,\n"
				+ "                    \"discountID\": \"5005\",\n"
				+ "                    \"extraInfo\": {\n"
				+ "                        \"discounts\": [\n"
				+ "                            {\n"
				+ "                                \"value\": -50.0,\n"
				+ "                                \"multiplier\": 1.0,\n"
				+ "                                \"applicable\": \"\",\n"
				+ "                                \"discountID\": \"5005\"\n"
				+ "                            }\n"
				+ "                        ],\n"
				+ "                        \"dates\": [\n"
				+ "                            {\n"
				+ "                                \"bookingFromDate\": \"2023-03-30\",\n"
				+ "                                \"bookingToDate\": \"2023-03-31\",\n"
				+ "                                \"stayFromDate\": \"2023-04-19\",\n"
				+ "                                \"stayToDate\": \"2023-04-20\"\n"
				+ "                            }\n"
				+ "                        ],\n"
				+ "                        \"applyToWeekDays\": \"M,T,W,Th,F,S,Su\",\n"
				+ "                        \"blockoutDates\": {\n"
				+ "                            \"blockOutBooking\": \"\",\n"
				+ "                            \"blockOutStay\": \"\"\n"
				+ "                        }\n"
				+ "                    }\n"
				+ "                }\n"
				+ "            },\n"
				+ "            \"ThemeData\": {\n"
				+ "                \"FontName\": \"Inter\",\n"
				+ "                \"WidgetPrimaryBgColor\": \"#f8f9fa\",\n"
				+ "                \"WidgetSecondaryBgColor\": \"#fff\",\n"
				+ "                \"WidgetFontColor\": \"#000\",\n"
				+ "                \"PrimaryColor\": \"#010c15\",\n"
				+ "                \"SecondaryColor\": \"#008fff\",\n"
				+ "                \"SubTitleColor\": \"#008fff\",\n"
				+ "                \"ContentColor\": \"#008fff\",\n"
				+ "                \"HyperLinkColor\": \"#008fff\",\n"
				+ "                \"MainBgColor\": \"#f2f3f3\",\n"
				+ "                \"SecondaryBgColor\": \"#f9fcfe\",\n"
				+ "                \"SecondaryBgFontColor\": \"#0d0d0d\",\n"
				+ "                \"PrimaryBtnFontColor\": \"#4e4844\",\n"
				+ "                \"PrimaryBtnBgColor\": \"#ffb800\",\n"
				+ "                \"SecondaryBtnFontColor\": \"#fff\",\n"
				+ "                \"SecondaryBtnBgColor\": \"#68869e\"\n"
				+ "            }\n"
				+ "        }\n"
				+ "    },\n"
				+ "    \"TrackingID\": \"12384425387-20230406073427-52064\"\n"
				+ "}\n"
				+ "";
	}
	public static String ComplexPayload() {
		return "{\n"
				+ "    \"empinfo\": {\n"
				+ "    	\"name\": \"onkar hajare \",\n"
				+ "    	\"position\": \"QA\",\n"
				+ "    	\"age\": \"22\"\n"
				+ "    	},\n"
				+ "    	\"skills\":[         \n"
				+ "    	 \n"
				+ "    	    {\n"
				+ "    	        \"programming\": \"java\",\n"
				+ "    	        \"scripting\": \"javascript\",\n"
				+ "    	        \"m1\": \"JRE\"\n"
				+ "    	        },\n"
				+ "    	        {\n"
				+ "    	        \"programming\": \"Python\",\n"
				+ "    	        \"scripting\": \"shellscript\",\n"
				+ "    	        \"m1\": \"JRE\"\n"
				+ "    	        }\n"
				+ "    	    ] , \n"
				+ "    	 \"Test\": [\n"
				+ "    	 		 {\n"
				+ "    	        \"Testx\": \"UnitTest1\",\n"
				+ "    	        \"Type\": \"Code\",\n"
				+ "    	        \"TRs\": \"123\"\n"
				+ "    	        },\n"
				+ "    	        {\n"
				+ "         		\"MaxOccupancy\": \"2\"\n"
				+ "		}\n"
				+ "    	 ]    \n"
				+ "}";
	}
		
	public static String BEPayload() {
		return "{\n"
				+ "	\"SellableProducts\": {\n"
				+ "		\"HotelCode\": \"TA1\",\n"
				+ "		\"SellableProduct\": [\n"
				+ "			{\n"
				+ "				\"InvStatusType\": \"Modify\",\n"
				+ "				\"GuestRoom\": {\n"
				+ "					\"Occupancy\": {\n"
				+ "						\"MaxOccupancy\": \"2\"\n"
				+ "					},\n"
				+ "					\"Room\": {\n"
				+ "						\"RoomID\": \"TT1\",\n"
				+ "						\"RoomRate\": \"2000\",\n"
				+ "						\"Quantity\": \"2\",\n"
				+ "						\"RoomType\": \"Apartment\",\n"
				+ "						\"SizeMeasurement\": \"16\",\n"
				+ "						\"SizeMeasurementUnit\": \"sqm\",\n"
				+ "						\"LicenseNumber\": \"AB-CD-1234\"\n"
				+ "					},\n"
				+ "					\"Facilities\": {\n"
				+ "						\"Facility\": [\n"
				+ "							{\n"
				+ "								\"Group\": \"Amenities\",\n"
				+ "								\"name\": \"Hairdyer\"\n"
				+ "							},\n"
				+ "							{\n"
				+ "								\"Group\": \"Amenities\",\n"
				+ "								\"name\": \"Free Wifi\"\n"
				+ "							},\n"
				+ "							{\n"
				+ "								\"Group\": \"Amenities\",\n"
				+ "								\"name\": \"Iron Facilities\"\n"
				+ "							},\n"
				+ "							{\n"
				+ "								\"Group\": \"Kitchen\",\n"
				+ "								\"name\": \"Microwave\"\n"
				+ "							},\n"
				+ "							{\n"
				+ "								\"Group\": \"Kitchen\",\n"
				+ "								\"name\": \"Coffee Maker\"\n"
				+ "							}\n"
				+ "						]\n"
				+ "					},\n"
				+ "					\"Images\": {\n"
				+ "						\"Image\": [\n"
				+ "							{\n"
				+ "								\"name\": \"demo\",\n"
				+ "								\"url\": \"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/how-to-get-upgraded-1565955358.jpg\"\n"
				+ "							},\n"
				+ "							{\n"
				+ "								\"name\": \"demo1\",\n"
				+ "								\"url\": \"https://i1.wp.com/www.turningleftforless.com/wp-content/uploads/2017/05/IMG_0012-2.jpg\"\n"
				+ "							},\n"
				+ "							{\n"
				+ "								\"name\": \"demo2\",\n"
				+ "								\"url\": \"https://www.thebalancesmb.com/thmb/Jg74vkkBq7xAZTqP-GdlgSZB5Mg=/3000x1687/smart/filters:no_upscale()/hotel_room-627892060-5a7a30d1642dca00370179e6.jpg\"\n"
				+ "							},\n"
				+ "							{\n"
				+ "								\"name\": \"demo3\",\n"
				+ "								\"url\": \"https://i.ytimg.com/vi/ebxAKwujN_k/maxresdefault.jpg\"\n"
				+ "							},\n"
				+ "							{\n"
				+ "								\"name\": \"demo4\",\n"
				+ "								\"url\": \"https://diamond-hotel-website-cdn-glocorpitsolutio.netdna-ssl.com/optimized_img/accommodations/deluxe1.jpg\"\n"
				+ "							}\n"
				+ "						]\n"
				+ "					},\n"
				+ "					\"Position\": {\n"
				+ "						\"Latitude\": \"49.4092\",\n"
				+ "						\"Longitude\": \"1.0900\"\n"
				+ "					},\n"
				+ "					\"Address\": {\n"
				+ "						\"AddressLine\": \"15 Station Street\",\n"
				+ "						\"CityName\": \"London\",\n"
				+ "						\"CountryName\": \"GB\",\n"
				+ "						\"PostalCode\": \"M16JD\"\n"
				+ "					},\n"
				+ "					\"Description\": {\n"
				+ "						\"Text\": \"Deluxe Double Room with Sea View\",\n"
				+ "						\"RoomDescription\": \"hello\"\n"
				+ "					}\n"
				+ "				}\n"
				+ "			}\n"
				+ "			\n"
				+ "			\n"
				+ "		]\n"
				+ "	}\n"
				+ "}";
	}
	
	public static String putrequestpayload() {
		return "{\n"
				+ "    \"name\": \"omkar\",\n"
				+ "    \"job\": \"Test president\"\n"
				+ "}";
	}
}
